version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio-test
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: devops123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    
  postgres:
    image: postgres:15
    container_name: postgres-test
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: devops123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  minio-data:
  postgres-data: