{
 "title": "Performance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Client Request Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "tester_request_duration_seconds{quantile=\"0.99\", status=\"200\", job=\"kubernetes-pods-annotated\", namespace=\"go-app\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"go-app.*\", container!=\"\", container!=\"POD\"}[5m])) by (container, pod) * 1000",
     "legendFormat": "{{ container }} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(tester_request_duration_seconds_count{status=\"200\", job=\"kubernetes-pods-annotated\", namespace=\"go-app\"}[5m])) by (container, pod)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"go-app.*\", container!=\"\", container!=\"POD\"} / 1024 / 1024",
     "legendFormat": "{{ container }} ({{ pod }})"
    }
   ]
  },
  {
   "title": "S3 Request Latency (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(myapp_request_duration_seconds_sum{job=\"kubernetes-pods-annotated\", namespace=\"go-app\", op=\"s3\"}[30s]) / rate(myapp_request_duration_seconds_count{job=\"kubernetes-pods-annotated\", namespace=\"go-app\", op=\"s3\"}[30s])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Database SQL Latency (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(myapp_request_duration_seconds_sum{job=\"kubernetes-pods-annotated\", namespace=\"go-app\", op=\"db\"}[30s]) / rate(myapp_request_duration_seconds_count{job=\"kubernetes-pods-annotated\", namespace=\"go-app\", op=\"db\"}[30s])",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}