apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-stack
  namespace: argo-cd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dimaserbenyuk/go-monitoring.git
    targetRevision: HEAD
    path: helm/Argo-application/network
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m